/**
 * Tailwind theme 扩展 — 与 theme.css `@theme inline` 对齐，供 IDE 提示与非 v4 消费方。
 * 运行时 Tailwind v4 以 theme.css 内 `@theme inline` 为准。
 */
/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: {
        brand: 'var(--brand)',
        'brand-dark': 'var(--brand-dark)',
        'brand-disabled': 'var(--brand-disabled)',
        'brand-light': 'var(--brand-light)',
        'brand-xlight': 'var(--brand-xlight)',
        'gray-border-black': 'var(--gray-border-black)',
        'gray-border-strong': 'var(--gray-border-strong)',
        'gray-border-normal': 'var(--gray-border-normal)',
        'gray-border-light': 'var(--gray-border-light)',
        'gray-border-exlight': 'var(--gray-border-exlight)',
        'gray-border-emphasis': 'var(--gray-border-emphasis)',
        'gray-text-1': 'var(--gray-text-1)',
        'gray-text-2': 'var(--gray-text-2)',
        'gray-text-3': 'var(--gray-text-3)',
        'gray-text-4': 'var(--gray-text-4)',
        'gray-text-5': 'var(--gray-text-5)',
        'gray-text-7': 'var(--gray-text-7)',
        'gray-fill-disabled': 'var(--gray-fill-disabled)',
        'gray-fill-strong': 'var(--gray-fill-strong)',
        'gray-fill-normal': 'var(--gray-fill-normal)',
        'gray-fill-light': 'var(--gray-fill-light)',
        'gray-fill-panel': 'var(--gray-fill-panel)',
        'page-bg': 'var(--page-bg)',
        'accent-orange': 'var(--accent-orange)',
        'accent-orange-bg': 'var(--accent-orange-bg)',
        'danger-dot': 'var(--danger-dot)',
        'portal-text-link': 'var(--portal-text-link)',
        'semantic-success-bg': 'var(--semantic-success-bg)',
        'semantic-success-light': 'var(--semantic-success-light)',
        'semantic-success-default': 'var(--semantic-success-default)',
        'semantic-success-text': 'var(--semantic-success-text)',
        'semantic-info-bg': 'var(--semantic-info-bg)',
        'semantic-info-light': 'var(--semantic-info-light)',
        'semantic-info-default': 'var(--semantic-info-default)',
        'semantic-info-text': 'var(--semantic-info-text)',
        'semantic-warning-bg': 'var(--semantic-warning-bg)',
        'semantic-warning-light': 'var(--semantic-warning-light)',
        'semantic-warning-default': 'var(--semantic-warning-default)',
        'semantic-warning-text': 'var(--semantic-warning-text)',
        'semantic-error-bg': 'var(--semantic-error-bg)',
        'semantic-error-light': 'var(--semantic-error-light)',
        'semantic-error-default': 'var(--semantic-error-default)',
        'semantic-error-text': 'var(--semantic-error-text)',
        'semantic-neutral-bg': 'var(--semantic-neutral-bg)',
        'semantic-neutral-light': 'var(--semantic-neutral-light)',
        'semantic-neutral-default': 'var(--semantic-neutral-default)',
        'semantic-neutral-text': 'var(--semantic-neutral-text)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
        checkbox: 'var(--radius-checkbox)',
        badge: 'var(--radius-badge)',
        input: 'var(--radius-input)',
        card: 'var(--radius-card)',
        'button-xs': 'var(--radius-button-xs)',
        'button-sm': 'var(--radius-button-sm)',
        btn: 'var(--radius-button)',
        'button-lg': 'var(--radius-button-lg)',
        cta: 'var(--radius-cta)',
        nav: 'var(--radius-nav)',
        modal: 'var(--radius-modal)',
      },
      fontFamily: {
        sans: ['var(--font-family-sans)'],
        mono: ['var(--font-family-mono)'],
      },
      lineHeight: {
        16: 'var(--leading-16)',
        20: 'var(--leading-20)',
        24: 'var(--leading-24)',
        28: 'var(--leading-28)',
        32: 'var(--leading-32)',
        40: 'var(--leading-40)',
      },
      fontSize: {
        11: ['var(--text-11)', { lineHeight: 'var(--leading-16)' }],
        12: ['var(--text-12)', { lineHeight: 'var(--leading-16)' }],
        /** @deprecated 同 text-13-compact */
        13: ['var(--text-13)', { lineHeight: 'var(--leading-16)' }],
        '13-compact': ['var(--text-13)', { lineHeight: 'var(--leading-16)' }],
        '13-reading': ['var(--text-13)', { lineHeight: 'var(--leading-20)' }],
        14: ['var(--text-14)', { lineHeight: 'var(--leading-20)' }],
        15: ['var(--text-15)', { lineHeight: 'var(--leading-20)' }],
        16: ['var(--text-16)', { lineHeight: 'var(--leading-24)' }],
        18: ['var(--text-18)', { lineHeight: 'var(--leading-28)' }],
        20: ['var(--text-20)', { lineHeight: 'var(--leading-28)' }],
        22: ['var(--text-22)', { lineHeight: 'var(--leading-28)' }],
        24: ['var(--text-24)', { lineHeight: 'var(--leading-32)' }],
        32: ['var(--text-32)', { lineHeight: 'var(--leading-40)' }],
      },
      boxShadow: {
        'focus-normal': 'var(--focus-ring-normal)',
        'focus-brand': 'var(--focus-ring-brand)',
      },
    },
  },
};
