/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: {
        brand: 'var(--brand)',
        'brand-dark': 'var(--brand-dark)',
        'brand-disabled': 'var(--brand-disabled)',
        'brand-light': 'var(--brand-light)',
        'brand-xlight': 'var(--brand-xlight)',
        'gray-border-strong': 'var(--gray-border-strong)',
        'gray-border-normal': 'var(--gray-border-normal)',
        'gray-border-light': 'var(--gray-border-light)',
        'gray-border-exlight': 'var(--gray-border-exlight)',
        'gray-border-emphasis': 'var(--gray-border-emphasis)',
        'gray-text-1': 'var(--gray-text-1)',
        'gray-text-2': 'var(--gray-text-2)',
        'gray-text-3': 'var(--gray-text-3)',
        'gray-text-4': 'var(--gray-text-4)',
        'gray-text-5': 'var(--gray-text-5)',
        'gray-text-7': 'var(--gray-text-7)',
        'gray-fill-disabled': 'var(--gray-fill-disabled)',
        'gray-fill-strong': 'var(--gray-fill-strong)',
        'gray-fill-normal': 'var(--gray-fill-normal)',
        'gray-fill-light': 'var(--gray-fill-light)',
        'page-bg': 'var(--page-bg)',
        'page-bg-list': 'var(--page-bg-list)',
        'page-bg-shell': 'var(--page-bg-shell)',
        'page-bg-quote': 'var(--page-bg-quote)',
        'accent-orange': 'var(--accent-orange)',
        'accent-orange-bg': 'var(--accent-orange-bg)',
        'danger-dot': 'var(--danger-dot)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
        section: 'var(--radius-lg)',
        cta: 'var(--radius-xl)',
        nav: 'var(--radius-lg)',
        modal: 'var(--radius-2xl)',
      },
      fontSize: {
        11: ['11px', { lineHeight: '16px' }],
        12: ['12px', { lineHeight: '16px' }],
        13: ['13px', { lineHeight: '18px' }],
        14: ['14px', { lineHeight: '20px' }],
        15: ['15px', { lineHeight: '20px' }],
        16: ['16px', { lineHeight: '24px' }],
        18: ['18px', { lineHeight: '28px' }],
        20: ['20px', { lineHeight: '28px' }],
        22: ['22px', { lineHeight: '1.375' }],
        24: ['24px', { lineHeight: '32px' }],
        32: ['32px', { lineHeight: '1.2' }],
      },
      boxShadow: {
        'focus-brand': 'var(--focus-ring-brand)',
      },
    },
  },
};
